### ISSUE TITLE
`Timeout (12s) waiting for privilege escalation prompt`

### ISSUE THREAD

**Issue by a-w-1806** [meonkeys/shb#2]
Hi. I am seeing this error.

```
❯ ❯ ./provision.sh
BECOME password:

PLAY [all] ********************************************************************************************************************************

TASK [base : Configure apt cache] *********************************************************************************************************
fatal: [mario_server]: FAILED! => {"msg": "Timeout (12s) waiting for privilege escalation prompt: "}

PLAY RECAP ********************************************************************************************************************************
mario_server               : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

1. What does "BECOME password" mean?
2. Why am I seeing this `privilege escalation prompt`?

## Update

Following https://stackoverflow.com/questions/39533532/ansible-timeout-12s-waiting-for-privilege-escalation-prompt can solve the issue. I think it makes sense if we add this in this repo.

**Comment by meonkeys** [comment]
Ahoy!

> I am seeing this error

Does this error occur every time you try to run `provision.sh`? Just checking if this issue is persistent or intermittent. I'm guessing the latter based on your other issues which clearly show your provision (almost) completing.

I can't reproduce the error on my server.

> What does "BECOME password" mean?

That's Ansible asking you for a password to assume root privileges (*become* root) to be able to make changes to the system, such as installing packages. Illustrated in the book in listing *mario second run output (🏠 admin computer)*.

> Following (stackoverflow 39533532) can solve the issue.

Do you know which answer?

**Comment by meonkeys** [comment]
I wonder if this is related to #5. What do you think?

**Comment by meonkeys** [comment]
Just a heads-up that I'll likely close issues after a while if they remain idle. When I do, please feel free to reopen them, open more/other issues, and use the [chat and forum](https://selfhostbook.com/contact/). I hope we can get your server up and running and working well.

**Comment by meonkeys** [comment]
Closing. Please see https://github.com/meonkeys/shb/issues/2#issuecomment-2200737880
